# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settings_ui(object):
    def setupUi(self, settings_ui):
        settings_ui.setObjectName("settings_ui")
        settings_ui.resize(278, 350)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(settings_ui)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabs = QtWidgets.QTabWidget(settings_ui)
        self.tabs.setTabBarAutoHide(False)
        self.tabs.setObjectName("tabs")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.interests = QtWidgets.QGroupBox(self.settings_tab)
        self.interests.setObjectName("interests")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.interests)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.interests)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_5.addWidget(self.interests)
        self.categories = QtWidgets.QGroupBox(self.settings_tab)
        self.categories.setObjectName("categories")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.categories)
        self.verticalLayout.setObjectName("verticalLayout")
        self.general = QtWidgets.QCheckBox(self.categories)
        self.general.setObjectName("general")
        self.verticalLayout.addWidget(self.general)
        self.anime = QtWidgets.QCheckBox(self.categories)
        self.anime.setObjectName("anime")
        self.verticalLayout.addWidget(self.anime)
        self.people = QtWidgets.QCheckBox(self.categories)
        self.people.setObjectName("people")
        self.verticalLayout.addWidget(self.people)
        self.verticalLayout_5.addWidget(self.categories)
        self.settings = QtWidgets.QGroupBox(self.settings_tab)
        self.settings.setObjectName("settings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nsfw = QtWidgets.QCheckBox(self.settings)
        self.nsfw.setStyleSheet("QCheckBox {\n"
"    color: red;\n"
"}")
        self.nsfw.setObjectName("nsfw")
        self.verticalLayout_3.addWidget(self.nsfw)
        self.label = QtWidgets.QLabel(self.settings)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.settings)
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(1000)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.verticalLayout_5.addWidget(self.settings)
        self.tabs.addTab(self.settings_tab, "")
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.about_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.desc = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.desc.setFont(font)
        self.desc.setObjectName("desc")
        self.verticalLayout_6.addWidget(self.desc)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.tabs.addTab(self.about_tab, "")
        self.verticalLayout_4.addWidget(self.tabs)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setObjectName("buttons")
        spacerItem1 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons.addItem(spacerItem1)
        self.close = QtWidgets.QPushButton(settings_ui)
        self.close.setObjectName("close")
        self.buttons.addWidget(self.close)
        self.verticalLayout_4.addLayout(self.buttons)

        self.retranslateUi(settings_ui)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_ui)

    def retranslateUi(self, settings_ui):
        _translate = QtCore.QCoreApplication.translate
        settings_ui.setWindowTitle(_translate("settings_ui", "Dialog"))
        self.interests.setTitle(_translate("settings_ui", "Interests"))
        self.categories.setTitle(_translate("settings_ui", "Categories"))
        self.general.setText(_translate("settings_ui", "General"))
        self.anime.setText(_translate("settings_ui", "Anime"))
        self.people.setText(_translate("settings_ui", "People"))
        self.settings.setTitle(_translate("settings_ui", "Settings"))
        self.nsfw.setText(_translate("settings_ui", "NSFW"))
        self.label.setText(_translate("settings_ui", "Delay (minutes)"))
        self.tabs.setTabText(self.tabs.indexOf(self.settings_tab), _translate("settings_ui", "Settings"))
        self.desc.setText(_translate("settings_ui", "<html><head/><body><p>Wallmaster - Dynamic Wallpaper Changer<br/><span style=\" font-weight:400;\">Version 1.0<br/>Copyright (C) Ognjen Galić<br/><br/>Licensed under the BSD 2-Clause license with<br/>theme exception. Theme is licensed under the<br/>GNU GPL.</span></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.about_tab), _translate("settings_ui", "About"))
        self.close.setText(_translate("settings_ui", "Close"))

